### PR TITLE
Remove relative links

### PR DESCRIPTION
**Pull request by thailekha**
JIRA: https://issues.jboss.org/browse/RHMAP-14051

Motivation: relative links become broken links in the Docs section on the studio

For this repo, ReadMe.md file was also renamed to README.md since the studio does not pick up ReadMe.md

### CODE REVIEW

**Review by rachael-oregan — APPROVED** [review]
LGTM, just need a version bump in a separate commit

**Comment by danielpassos** [comment]
@thailekha I think this is the only one I can't merge, because there is a CI is required.

**Comment by thailekha** [comment]
retest this please

**Comment by thailekha** [comment]
Retest this please

**Comment by danielpassos** [comment]
I have created an issues to fix _Xamarin_ builds and going to merge it 

https://issues.jboss.org/browse/FH-3437

**Pull request merged**
